source :rubygems
gem 'rails', '3.0.0'
gem 'pg'
gem 'devise'
gem 'formtastic'
gem 'validation_reflection'
gem 'paperclip'
gem 'aws-s3', :require => 'aws/s3'
gem 'savon'
gem 'savon_model', :git => 'git://github.com/rubiii/savon_model.git', :branch => 'dev'